### ISSUE TITLE
Exception has occurred: InvalidSchema

### ISSUE THREAD

**Issue by kyuchin** [sj-dan/OpenSea-NFT-Stealer#20] opened 2022-01-20 23:01 UTC
No connection adapters were found for 'ipfs://QmRRPWG96cmgTn2qSzjwr2qvfNEuhunv6FNeMFGa9bx6mQ'
  File "C:\Users\Gaming\Desktop\OpenSea-NFT-Stealer-master\opensea.py", line 98, in <module>
    image = requests.get(asset["image_original_url"])

**Comment by sj-dan** [comment] 2022-01-21 14:00
Duplicate of #15

**Closed as completed by sj-dan** 2022-01-21 14:00 UTC
Labels: duplicate
